# Generated by Django 5.0.4 on 2024-04-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
