# Generated by Django 5.0.4 on 2024-04-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='department',
            field=models.CharField(choices=[('b', 'Backend'), ('f', 'Frontend'), ('n', 'Network')], max_length=20),
        ),
    ]
