# Generated by Django 5.0.4 on 2024-04-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_alter_trainer_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='department',
            field=models.CharField(choices=[('b', 'Backend'), ('f', 'Frontend'), ('n', 'Network')], max_length=20, null=True),
        ),
    ]
