# Generated by Django 5.0.4 on 2024-04-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_alter_trainer_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='department',
            field=models.CharField(choices=[('f', 'Frontend'), ('b', 'Backend'), ('n', 'Network')], max_length=20, null=True),
        ),
    ]
