# Generated by Django 5.0.4 on 2024-05-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_alter_trainer_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='department',
            field=models.CharField(choices=[('f', 'Frontend'), ('n', 'Network'), ('b', 'Backend')], max_length=20, null=True),
        ),
    ]
