# Generated by Django 5.0.4 on 2024-05-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_alter_trainer_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='department',
            field=models.CharField(choices=[('n', 'Network'), ('b', 'Backend'), ('f', 'Frontend')], max_length=20, null=True),
        ),
    ]
