# Generated by Django 5.0.4 on 2024-05-13 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_gender'),
        ('trainer', '0010_alter_trainer_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.trainer'),
        ),
    ]
