# Generated by Django 5.0.4 on 2024-05-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
